name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend_test:
    runs-on: ubuntu-latest

    env:
      MONGO_URL: mongodb+srv://FCaetano:FCaetano@cluster0.erktrrv.mongodb.net/concesionaria_test?retryWrites=true&w=majority&appName=Cluster0
      NODE_ENV: test
      JWT_SECRET: test_jwt_secret_key_for_ci
    
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias Backend
        run: npm install

      - name: Lint del c√≥digo Backend
        run: npm run lint

      - name: Ejecutar pruebas Backend
        run: npm test
        env:
          CI: true

  frontend_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias Frontend
        run: npm install

      - name: Ejecutar pruebas Frontend
        run: npm test -- --watchAll=false

      - name: Build Frontend
        run: npm run build
